name: voila-NV-energy-project
channels:
- conda-forge
dependencies:
- jupyterlab>=3.1
- kafka-python==2.0.2
- sparkdl==0.2.2
- keras==2.11.0
- nbconvert==0.7.2
- ipympl==0.9.3
- ipywidgets==8.0.2
- py4j==0.10.9.5
- sqlparse==0.4.3
- tensorboard==2.11.2
- tensorboard-data-server==0.6.1
- tensorboard-plugin-wit==1.8.1
- tensorflow==2.11.0
- tensorflow-estimator==2.11.0
- tensorflow-io-gcs-filesystem==0.31.0
- tensorflowonspark==2.2.5
- tensorframes==0.2.9
- termcolor==2.2.0
- virtualenv==20.21.0
- voila==0.4.0
- xgboost==1.5.0
